### ISSUE TITLE
wrong city name

### ISSUE THREAD

**Issue by DirektX** [SixBytesUnder/custom-motd#10]
This is wrong:
City Name = "Stuhlweissenburg, HU" Location = "EUR|HU|HU011|SZÉKESFEHÉRVAR" Country = "Hungary"
It is corrected:
City Name = "Szekesfehervar, HU" Location = "EUR|HU|HU011|SZÉKESFEHÉRVÁR" Country = "Hungary"

**Comment by SixBytesUnder** [comment]
Thanks for pointing it out. The file with those codes was downloaded from Acuweather long time ago.
I've corrected it in https://github.com/SixBytesUnder/custom-motd/commit/b0ec85d603765c31aed5a09b69f2212595b665de
