### ISSUE TITLE
Public IP visible in commit history

### ISSUE THREAD

**Issue by ghost** [SixBytesUnder/custom-motd#7]
The public IP of the creator is visible in de commit history.

**Comment by SixBytesUnder** [comment]
Hi @Tim-Hobbes 
If you're referring to the screenshot in one of the first commits, then don't worry as I have changed internet provider since and also my external IP address is dynamic.

If you're talking about a different place, then please be a bit more specific.

**Comment by ghost** [comment]
Yes, I was referring to that screenshot. It is nice to hear that it won't pose a security threat.

**Comment by SixBytesUnder** [comment]
No worries, thanks for flagging it :)
